### ISSUE TITLE
epubmaker（DEBUGモード）でエクスポートを指定すると Errno::EEXIST エラー発生　

### ISSUE THREAD

**Issue by goto-yuki** [kmuto/review#1265]
# epubmakerで Errno::EEXIST エラー発生

```
$ review-epubmaker config.yml test
DEBUG: Loaded yaml file (config.yml). I will produce test.epub.
Traceback (most recent call last):
        5: from /usr/local/bin/review-epubmaker:23:in `<main>'
        4: from /usr/local/bin/review-epubmaker:23:in `load'
        3: from /var/lib/gems/2.5.0/gems/review-3.0.0/bin/review-epubmaker:48:in `<top (required)>'
        2: from /var/lib/gems/2.5.0/gems/review-3.0.0/lib/review/epubmaker.rb:111:in `produce'
        1: from /var/lib/gems/2.5.0/gems/review-3.0.0/lib/review/epubmaker.rb:84:in `build_path'
/var/lib/gems/2.5.0/gems/review-3.0.0/lib/review/epubmaker.rb:84:in `mkdir': File exists @ dir_s_mkdir - /mnt/e/Users/review3/test/epubmaker/book-epub (Errno::EEXIST)
```

## エラー発生条件

- DEBUGモード
- export_filenameを指定する　（指定しなければ発生しない）
- 2回目以降（初回は発生しない）

```
$ review-epubmaker config.yml test
```
1回目の実行で、book-epubディレクトリが作成されます。
2回目の実行で、book-epubディレクトリの mkdir で: File existsエラーとなります。book-epubディレクトリを手動で削除すればOKです。

**Comment by kmuto** [comment]
これはむしろexport_filenameオプションを廃止したほうがいいだろうか…

**Comment by goto-yuki** [comment]
類似の問題を発見しました。

# pdfmakerで Errno::EEXIST エラー発生

```
$ review-pdfmaker config.yml
Traceback (most recent call last):
        7: from /usr/local/bin/review-pdfmaker:23:in `<main>'
        6: from /usr/local/bin/review-pdfmaker:23:in `load'
        5: from /var/lib/gems/2.5.0/gems/review-3.0.0/bin/review-pdfmaker:16:in `<top (required)>'
        4: from /var/lib/gems/2.5.0/gems/review-3.0.0/lib/review/pdfmaker.rb:97:in `execute'
        3: from /var/lib/gems/2.5.0/gems/review-3.0.0/lib/review/pdfmaker.rb:156:in `execute'
        2: from /var/lib/gems/2.5.0/gems/review-3.0.0/lib/review/pdfmaker.rb:256:in `generate_pdf'
        1: from /var/lib/gems/2.5.0/gems/review-3.0.0/lib/review/pdfmaker.rb:79:in `build_path'
/var/lib/gems/2.5.0/gems/review-3.0.0/lib/review/pdfmaker.rb:79:in `mkdir': File exists @ dir_s_mkdir - book-pdf (Errno::EEXIST)
```
## エラー発生条件

* DEBUGモード
* 2回目以降（初回は発生しない）

**Comment by kmuto** [comment]
はて… epubmaker（lib/review/epubmaker.rb）、pdfmaker（lib/review/pdfmaker.rb）ともに
```
  def build_path
      if @config['debug']
        path = File.expand_path("#{@config['bookname']}-epub", Dir.pwd)
        if File.exist?(path)
          FileUtils.rm_rf(path, secure: true)
        end
        Dir.mkdir(path)
        path
```
というかんじで、作業フォルダがあったらまず消すようにしているので、Ruby環境の問題？（エラー行番号からも一致してるように見えます）
OSはなんでしょう？

**Comment by goto-yuki** [comment]
Ruby環境の問題だったら、時間を取らせて申し訳ありません。

OSは、WSL(Windows Subsystem for LinuxL)でインストールしたUbuntuです。

作業用のファイルは、Windowsディレクトリをマウントしています。 
　　　 /mnt/e/Users/review3/test/epubmaker/book-epub (Errno::EEXIST)

WindowsとUbuntuを融合させた特殊な環境です。

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

**Comment by goto-yuki** [comment]
WSL個有の問題のようで、ご迷惑をかけました。
ありがとうございました。
