### ISSUE TITLE
escapeHTMLにnilが入ってくるケースがある

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1545]
```
elemental{kmuto}% rake web 
review-webmaker  config.yml
Traceback (most recent call last):
	13: from /home/kmuto/review/bin/review-webmaker:15:in `<main>'
	12: from /home/kmuto/review/lib/review/webmaker.rb:47:in `execute'
	11: from /home/kmuto/review/lib/review/webmaker.rb:99:in `execute'
	10: from /home/kmuto/review/lib/review/webmaker.rb:116:in `generate_html_files'
	 9: from /home/kmuto/review/lib/review/webmaker.rb:247:in `copy_frontmatter'
	 8: from /home/kmuto/review/lib/review/webmaker.rb:262:in `build_indexpage'
	 7: from /home/kmuto/review/lib/review/webmaker.rb:262:in `open'
	 6: from /home/kmuto/review/lib/review/webmaker.rb:279:in `block in build_indexpage'
	 5: from /home/kmuto/review/lib/review/template.rb:20:in `result'
	 4: from /usr/lib/ruby/2.5.0/erb.rb:876:in `result'
	 3: from /usr/lib/ruby/2.5.0/erb.rb:876:in `eval'
	 2: from (erb):14:in `block in build_indexpage'
	 1: from /home/kmuto/review/lib/review/makerhelper.rb:28:in `h'
/home/kmuto/review/lib/review/makerhelper.rb:28:in `escapeHTML': no implicit conversion of nil into String (TypeError)
rake aborted!
Command failed with status (1): [review-webmaker  config.yml...]
lib/tasks/review.rake:117:in `block in <top (required)>'
Tasks: TOP => web => webroot
(See full trace by running task with --trace)
```

今は詳細見られないので、あとで深追いしてみます。

**Comment by kmuto** [comment]
WebMakerのテンプレートがそもそもおかしかった
