### ISSUE TITLE
章にnonumを使うとエラー

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1566]
IndexBuilderに対して
```
=[nonum] CH02
```
のようにnonum付きのものを入れると

```
Traceback (most recent call last):
	18: from /home/kmuto/review/bin/review2top:186:in `<main>'
	17: from /home/kmuto/review/bin/review2top:29:in `main'
	16: from /home/kmuto/review/bin/review2top:84:in `_main'
	15: from /home/kmuto/review/bin/review2top:84:in `each'
	14: from /home/kmuto/review/bin/review2top:89:in `block in _main'
	13: from /home/kmuto/review/lib/review/compiler.rb:44:in `compile'
	12: from /home/kmuto/review/lib/review/compiler.rb:258:in `do_compile'
	11: from /home/kmuto/review/lib/review/builder.rb:57:in `bind'
	10: from /home/kmuto/review/lib/review/book/base.rb:132:in `generate_indexes'
	 9: from /home/kmuto/review/lib/review/book/base.rb:170:in `each_chapter'
	 8: from /home/kmuto/review/lib/review/book/base.rb:170:in `each'
	 7: from /home/kmuto/review/lib/review/book/chapter.rb:59:in `generate_indexes'
	 6: from /home/kmuto/review/lib/review/book/book_unit.rb:53:in `generate_indexes'
	 5: from /home/kmuto/review/lib/review/book/book_unit.rb:44:in `execute_indexer'
	 4: from /home/kmuto/review/lib/review/compiler.rb:44:in `compile'
	 3: from /home/kmuto/review/lib/review/compiler.rb:269:in `do_compile'
	 2: from /home/kmuto/review/lib/review/compiler.rb:367:in `compile_headline'
	 1: from /home/kmuto/review/lib/review/compiler.rb:414:in `open_tagged_section'
/home/kmuto/review/lib/review/index_builder.rb:102:in `nonum_begin': index -1 too small for array; minimum: 0 (IndexError)
```

となります。headlineと同じように即returnさせればいいのかな。

```
    def headline(level, label, caption)
      @sec_counter.inc(level)
      return if level < 2
```

**Comment by kmuto** [comment]
nodispとかも同じ
