### ISSUE TITLE
========という行が行頭にあると例外エラーになる

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1591]
見出しかどうかの判定がちょっと難しめですが…
特に=の数が多量の場合、ランタイムエラーになるのはよくなさそうです。

```
Traceback (most recent call last):
	15: from /home/kmuto/review/bin/review2html:184:in `<main>'
	14: from /home/kmuto/review/bin/review2html:29:in `main'
	13: from /home/kmuto/review/bin/review2html:83:in `_main'
	12: from /home/kmuto/review/bin/review2html:83:in `each'
	11: from /home/kmuto/review/bin/review2html:88:in `block in _main'
	10: from /home/kmuto/review/lib/review/compiler.rb:44:in `compile'
	 9: from /home/kmuto/review/lib/review/compiler.rb:260:in `do_compile'
	 8: from /home/kmuto/review/lib/review/builder.rb:51:in `bind'
	 7: from /home/kmuto/review/lib/review/book/chapter.rb:59:in `generate_indexes'
	 6: from /home/kmuto/review/lib/review/book/book_unit.rb:53:in `generate_indexes'
	 5: from /home/kmuto/review/lib/review/book/book_unit.rb:44:in `execute_indexer'
	 4: from /home/kmuto/review/lib/review/compiler.rb:44:in `compile'
	 3: from /home/kmuto/review/lib/review/compiler.rb:271:in `do_compile'
	 2: from /home/kmuto/review/lib/review/compiler.rb:398:in `compile_headline'
	 1: from /home/kmuto/review/lib/review/index_builder.rb:86:in `headline'
/home/kmuto/review/lib/review/sec_counter.rb:24:in `inc': undefined method `+' for nil:NilClass (NoMethodError)
```

**Comment by takahashim** [comment]
これってどういう文書に対するエラーなんでしょうか？（タイトルだけでは意味が分かりませんでした）

**Comment by kmuto** [comment]
そうですよね、すみません。
届いた草稿をとりあえずRe:VIEW化して作業しようとしたのですが、

```
以上です。

=========

まとめ
```

という内容で上記例外になったのでした。=の前後は空白なしです。

ちなみにサポート範囲のレベルにして前後空白なしだと、

```
以上です。

======

まとめ
```

- TeX: `\subparagraph*{}`
- text: `■H6`
- HTML: 空行
- IDGXML: `<title aid:pstyle="h6"></title>`

になりますね。

**Comment by kmuto** [comment]
8文字以上だとどのビルダでも最初のsec_counterの例外。
7文字だとビルダのほうでエラーチェックしているもののIDGXMLがいまいちなので直さないと…

```
$ cat s.re
= test

=======

$ review2latex s.re
WARN review2latex: s.re:3: headline is empty.
WARN review2latex: s.re:3: headline is empty.
ERROR review2latex: s.re:3: error: unknown level: 7

$ review2top s.re
WARN review2top: s.re:3: headline is empty.
WARN review2top: s.re:3: headline is empty.
■H1■第1章　TEST
■H7■

$ review2html s.re
WARN review2html: s.re:3: headline is empty.
WARN review2html: s.re:3: headline is empty.
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
 ...
<h1><a id="h1"></a><span class="secno">第1章　</span>TEST</h1>

</body>
</html>
$ review2idgxml s.re
WARN review2idgxml: s.re:3: headline is empty.
WARN review2idgxml: s.re:3: headline is empty.
Traceback (most recent call last):
	8: from /home/kmuto/review/bin/review2idgxml:184:in `<main>'
	7: from /home/kmuto/review/bin/review2idgxml:29:in `main'
	6: from /home/kmuto/review/bin/review2idgxml:83:in `_main'
	5: from /home/kmuto/review/bin/review2idgxml:83:in `each'
	4: from /home/kmuto/review/bin/review2idgxml:88:in `block in _main'
	3: from /home/kmuto/review/lib/review/compiler.rb:44:in `compile'
	2: from /home/kmuto/review/lib/review/compiler.rb:273:in `do_compile'
	1: from /home/kmuto/review/lib/review/compiler.rb:400:in `compile_headline'
/home/kmuto/review/lib/review/idgxmlbuilder.rb:163:in `headline': caption level too deep or unsupported: 7 (RuntimeError)
```

**Comment by takahashim** [comment]
この件ですが、↓こんな感じのエラーで良いでしょうか？

### review-compileを使った場合

```
$ review-compile --target=html hoge.re 
ERROR review-compile: Invalid header: max headline level is 6
```

### Rakeを使った場合

```
review-epubmaker  config.yml
WARN review-epubmaker: compile error in hoge.re (ReVIEW::CompileError)
WARN review-epubmaker: Invalid header: max headline level is 6
compile error, No EPUB file output.
rake aborted!
```

**Comment by kmuto** [comment]
よさそうなかんじがします!

**Comment by takahashim** [comment]
マージしておきました
