### ISSUE TITLE
不正な追加セクション見出しを付けたときにreview-volだけバックトレースになってしまう

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1604]
```
= HELLO
==[unknown]
```
(unknownという囲み形式は存在しない)

```
$ review-compile --target html s.re
WARN review-compile: s.re:2: headline is empty.
ERROR review-compile: s.re:2: error: builder does not support tagged section: unknown
```

```
$ review-index
WARN review-index: s.re:2: headline is empty.
ERROR review-index: s.re:2: error: builder does not support tagged section: unknown
```

```
$ review-vol
WARN review-vol: s.re:2: headline is empty.
Traceback (most recent call last):
	20: from /home/kmuto/review/bin/review-vol:20:in `<main>'
	19: from /home/kmuto/review/lib/review/volumeprinter.rb:20:in `execute'
	18: from /home/kmuto/review/lib/review/volumeprinter.rb:40:in `execute'
	17: from /home/kmuto/review/lib/review/book/base.rb:153:in `each_part'
	16: from /home/kmuto/review/lib/review/book/base.rb:153:in `each'
	15: from /home/kmuto/review/lib/review/volumeprinter.rb:44:in `block in execute'
	14: from /home/kmuto/review/lib/review/book/part.rb:76:in `each_chapter'
	13: from /home/kmuto/review/lib/review/book/part.rb:76:in `each'
	12: from /home/kmuto/review/lib/review/volumeprinter.rb:45:in `block (2 levels) in execute'
	11: from /home/kmuto/review/lib/review/volumeprinter.rb:75:in `print_chapter_volume'
	10: from /home/kmuto/review/lib/review/builder.rb:51:in `bind'
	 9: from /home/kmuto/review/lib/review/book/chapter.rb:59:in `generate_indexes'
	 8: from /home/kmuto/review/lib/review/book/book_unit.rb:53:in `generate_indexes'
	 7: from /home/kmuto/review/lib/review/book/book_unit.rb:44:in `execute_indexer'
	 6: from /home/kmuto/review/lib/review/compiler.rb:46:in `compile'
	 5: from /home/kmuto/review/lib/review/compiler.rb:273:in `do_compile'
	 4: from /home/kmuto/review/lib/review/compiler.rb:391:in `compile_headline'
	 3: from /home/kmuto/review/lib/review/compiler.rb:426:in `open_tagged_section'
	 2: from /home/kmuto/review/lib/review/compiler.rb:696:in `error'
	 1: from /home/kmuto/review/lib/review/index_builder.rb:610:in `error'
/home/kmuto/review/lib/review/builder.rb:503:in `error': s.re:2: error: builder does not support tagged section: unknown (ReVIEW::ApplicationError)
```

review-volもこのエラーを拾う必要あり。

**Comment by kmuto** [comment]
`//iamge`みたいなタグエラーでもreview-volが壊れたので、ともかくindex_builderの例外を拾うようにしておくのがよさそう。
