### ISSUE TITLE
Debian stableのRubyでsafe_load_fileエラー

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1774]
やっぱりコード内でバージョン見て分けるとかしないとダメそうです。

```
$ ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
$ cd review/samples/sample-book/src
$ rake pdf
review-pdfmaker  config.yml
Traceback (most recent call last):
	4: from /home/kmuto/review/bin/review-pdfmaker:14:in `<main>'
	3: from /home/kmuto/review/lib/review/pdfmaker.rb:93:in `execute'
	2: from /home/kmuto/review/lib/review/pdfmaker.rb:124:in `execute'
	1: from /home/kmuto/review/lib/review/configure.rb:157:in `create'
/home/kmuto/review/lib/review/yamlloader.rb:20:in `load_file': undefined method `safe_load_file' for Psych:Module (NoMethodError)
Did you mean?  safe_load
	4: from /home/kmuto/review/bin/review-pdfmaker:14:in `<main>'
	3: from /home/kmuto/review/lib/review/pdfmaker.rb:93:in `execute'
	2: from /home/kmuto/review/lib/review/pdfmaker.rb:124:in `execute'
	1: from /home/kmuto/review/lib/review/configure.rb:155:in `create'
/home/kmuto/review/lib/review/configure.rb:159:in `rescue in create': yaml error undefined method `safe_load_file' for Psych:Module (ReVIEW::ConfigError)
Did you mean?  safe_load
rake aborted!
Command failed with status (1): [review-pdfmaker  config.yml...]
lib/tasks/review.rake:112:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => pdf => book.pdf
(See full trace by running task with --trace)
$ rake epub
review-epubmaker  config.yml
Traceback (most recent call last):
	4: from /home/kmuto/review/bin/review-epubmaker:15:in `<main>'
	3: from /home/kmuto/review/lib/review/epubmaker.rb:48:in `execute'
	2: from /home/kmuto/review/lib/review/epubmaker.rb:78:in `execute'
	1: from /home/kmuto/review/lib/review/configure.rb:157:in `create'
/home/kmuto/review/lib/review/yamlloader.rb:20:in `load_file': undefined method `safe_load_file' for Psych:Module (NoMethodError)
Did you mean?  safe_load
	4: from /home/kmuto/review/bin/review-epubmaker:15:in `<main>'
	3: from /home/kmuto/review/lib/review/epubmaker.rb:48:in `execute'
	2: from /home/kmuto/review/lib/review/epubmaker.rb:78:in `execute'
	1: from /home/kmuto/review/lib/review/configure.rb:155:in `create'
/home/kmuto/review/lib/review/configure.rb:159:in `rescue in create': yaml error undefined method `safe_load_file' for Psych:Module (ReVIEW::ConfigError)
Did you mean?  safe_load
rake aborted!
Command failed with status (1): [review-epubmaker  config.yml...]
lib/tasks/review.rake:117:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => epub => book.epub
(See full trace by running task with --trace)
$ cd ~/review
$ rake test
Bundler not found
/usr/bin/ruby2.7 test/run_test.rb
Loaded suite test
Started
...E
===============================================================================
Error: test_contentdir(BookTest):
  ReVIEW::ConfigError: yaml error undefined method `safe_load_file' for Psych:Mo
dule
  Did you mean?  safe_load
 ...
```

**Comment by takahashim** [comment]
うーん、わざわざunsafeなメソッドを使わせるのも良くないのでは…という気もするので、

* psych v3.3.2をインストールして使う
* 環境を分離させたいのであればbundlerを使う

をおすすめしたいところなのですが、どのへんがまずいでしょうか？

**Comment by takahashim** [comment]
（それはさておき、 #1775 みたいなのをsafe_loadで何とかできないか調べてみています）

**Comment by kmuto** [comment]
基本スタンスとして、Debian/Ubuntuにおいて公式debパッケージにないものを機能拡張以外で利用しなければいけない、という状況は避けたいと考えています。
unsafeについては、実際のところRe:VIEWの仕組み的にもともとユーザーがシェルで動かすものですし、ext・hook・graph・erb等ほかにいくらでもインジェクションする余地があるので、あまり気にしても仕方がないように思ってもおります…。
