### ISSUE TITLE
review-peg 0.1.1 テーブル内で改行すると意図しない.texが作成される

### ISSUE THREAD

**Issue by vvakame** [kmuto/review#459]
```
= ほげ

//table[hoge][ほげほげ]{
タイトル1
ぴよぴよ。@<br>{}ぷよぷよ。
//}
```

```
\chapter{ほげ}
\label{chap:tomorrowkey}
\begin{table}[h]
\reviewtablecaption{ほげほげ}
\label{table:tomorrowkey:hoge}
\begin{reviewtable}{|l|}
\hline
\reviewth{タイトル1}
 \\  \hline
\reviewth{\shortstack[l]{ぴよぴよ。\\}}
 \\  \hline
\reviewth{ぷよぷよ。}
 \\  \hline
\end{reviewtable}
\end{table}
```

```
! Misplaced \cr.
\reserved@c ->\cr
                  \ignorespaces
l.10 \reviewth{\shortstack[l]{ぴよぴよ。\\}}

?
```

review-compile 1.7.0 での出力は以下の通り…

```
\chapter{ほげ}
\label{chap:tomorrowkey}
\begin{table}[h]
\reviewtablecaption{ほげほげ}
\label{table:tomorrowkey:hoge}
\begin{reviewtable}{|l|}
\hline
\reviewth{タイトル1} \\  \hline
\reviewth{\shortstack[l]{ぴよぴよ。\\
ぷよぷよ。}} \\  \hline
\end{reviewtable}
\end{table}
```

**Comment by takahashim** [comment]
フィードバックありがとうございます！
https://github.com/kmuto/review/commit/6b3156a7f919a1fc4959bd5bab5c3fa5f4bab447 で修正してみました。review-peg 0.1.2だと、以下のようになるはずです。

```
$ review-compile-peg --target=latex tomorrowkey.re 
\chapter{ほげ}
\label{chap:tomorrowkey}
\begin{table}[h]
\reviewtablecaption{ほげほげ}
\label{table:tomorrowkey:hoge}
\begin{reviewtable}{|l|}
\hline
\reviewth{タイトル1} \\  \hline
\reviewth{\shortstack[l]{ぴよぴよ。\\
ぷよぷよ。}} \\  \hline
\end{reviewtable}
\end{table}
```

**Comment by vvakame** [comment]
あざます！
しかし別のエラーが出るようになりました…
どうやら、ラベルに _ があるとダメなようです。

```
= ほげ

//table[a_b][a_bとc]{
ほげ	ぴよ
//}
```

```
\chapter{ほげ}
\label{chap:tomorrowkey}
\begin{table}[h]
\reviewtablecaption{a\textunderscore{}bとc}
\label{table:tomorrowkey:a\textunderscore{}b}
\begin{reviewtable}{|l|l|}
\hline
\reviewth{ほげ} & ぴよ \\  \hline
\end{reviewtable}
\end{table}
```

```
Overfull \hbox (65.43587pt too wide) in paragraph at lines 252--262
[][]
[27] (./book.aux
! Missing \endcsname inserted.
<to be read again>
                   \T1\textunderscore
l.79 ...13}{a\textunderscore {}bとc}{table.2.1}{}}

?
```

review-compile 1.7.0 での出力は以下の通り…

```
\chapter{ほげ}
\label{chap:tomorrowkey}
\begin{table}[h]
\reviewtablecaption{a\textunderscore{}bとc}
\label{table:tomorrowkey:a_b}
\begin{reviewtable}{|l|l|}
\hline
\reviewth{ほげ} & ぴよ \\  \hline
\end{reviewtable}
\end{table}
```

**Comment by takahashim** [comment]
@vvakame ううう…すみません。
idはエスケープされないよう修正しました。review-peg 0.1.3でお願いします :bow:

**Comment by vvakame** [comment]
通るようになりました！ありがとうございます。

**Comment by vvakame** [comment]
ずびばせんreopenします…。

```
= a

@<table>{f_m}

//table[f_m][desc]{
a	te
//}
```

上記パターンがうまく処理できないようです。エラーメッセージは以下の通り。

```
$ bundle exec review-compile-peg --target=latex articles/keiji_ariyama.re
/Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/book/index.rb:71:in `rescue in []': not found key 'f\textunderscore{}m' for ReVIEW::Book::TableIndex (ReVIEW::KeyError)
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/book/index.rb:58:in `[]'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/book/compilable.rb:96:in `table'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/latexbuilder.rb:702:in `inline_table'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/compiler.rb:808:in `compile_inline'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:138:in `to_doc'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:24:in `block in to_s_by'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:24:in `map'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:24:in `to_s_by'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:12:in `to_doc'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:24:in `block in to_s_by'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:24:in `map'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:24:in `to_s_by'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:12:in `to_doc'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:72:in `to_doc'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:24:in `block in to_s_by'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:24:in `map'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:24:in `to_s_by'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/node.rb:12:in `to_doc'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/compiler.rb:409:in `convert_ast'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/compiler.rb:398:in `do_compile'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/lib/review/compiler.rb:390:in `compile'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/bin/review-compile-peg:157:in `block in _main'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/bin/review-compile-peg:153:in `each'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/bin/review-compile-peg:153:in `_main'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/bin/review-compile-peg:31:in `main'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.3/bin/review-compile-peg:202:in `<top (required)>'
	from /Users/vvakame/.rbenv/versions/2.2.3/bin/review-compile-peg:23:in `load'
	from /Users/vvakame/.rbenv/versions/2.2.3/bin/review-compile-peg:23:in `<main>'
```

3行目をコメントアウトするとエラーが変化します。
IDをf_mからa_bに変更するとなぜかコンパイルが通る件について…。

**Comment by vvakame** [comment]
その他、あまり詳しく見てないですが以下のパターンもだめそう。
全てtarget=latexです。

```
//image[install-language-review][language-reviewをインストールする]{
//}
```

```
>> /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/book/index.rb:71:in `rescue in []': not found key 'install{-}language{-}review' for ReVIEW::Book::IndepImageIndex (ReVIEW::KeyError)
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/book/index.rb:58:in `[]'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/book/compilable.rb:117:in `image'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/latexbuilder.rb:701:in `inline_img'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/compiler.rb:808:in `compile_inline'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/node.rb:138:in `to_doc'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/node.rb:24:in `block in to_s_by'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/node.rb:24:in `map'
>> from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/node.rb:24:in `to_s_by'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/node.rb:12:in `to_doc'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/node.rb:24:in `block in to_s_by'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/node.rb:24:in `map'
```

また

```
詳細は@<chapref>{review-introduction}に譲ります。
```

```
>> /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/book/index.rb:101:in `rescue in number'
>> : invalid number error: id:review{-}introduction, capter: (RuntimeError)
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/book/index.rb:94:in `number'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/book/index.rb:111:in `display_string'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/builder.rb:197:in `inline_chapref'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/latexbuilder.rb:652:in `inline_chapref'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/compiler.rb:808:in `compile_inline'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/node.rb:138:in `to_doc'
>> 	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.1.1/lib/review/node.rb:24:in `block in to_s_by'
```

なお

```
$ cat review-introduction.tex
\chapter{Re:VIEWの書き方}
\label{chap:review-introduction}

TODO mstssk
\section{記法の紹介}
\label{sec:3-1}
...
```

**Comment by vvakame** [comment]
footnoteについて

```
//footnote[url][TechBoosterのWebサイト @<href>{http://techbooster.org/}]
```

が

```
\footnote{TechBoosterのWebサイト @\textless{}href\textgreater{}\{http://techbooster.org/\}}
```

となります。

<img width="349" alt="c89-firststepreview-v2_pdf" src="https://cloud.githubusercontent.com/assets/125332/11168806/e751fd90-8be3-11e5-9fff-7d292eeec2cc.png">

**Comment by vvakame** [comment]
これ、個別にIssueたてたほうがいいですかね…？今後、どうしましょうか。

**Comment by vvakame** [comment]
review-peg 0.2.0 が出たのに気がついた顔をしてるマンです。
すみませんもう一回確認して報告します。
