### ISSUE TITLE
review-peg 0.2.0 コラムのタイトルに - が含まれているとコンパイルがコケる

### ISSUE THREAD

**Issue by vvakame** [kmuto/review#462]
```
$ review-compile-peg -v
review-compile-peg 0.2.0
$ cat test.re
= foo

==[column] a-b
$ review-compile-peg --target=latex test.re
/Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/book/index.rb:71:in `rescue in []': not found key 'a{-}b' for ReVIEW::Book::ColumnIndex (ReVIEW::KeyError)
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/book/index.rb:58:in `[]'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/book/compilable.rb:167:in `column'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/latexbuilder.rb:438:in `column_label'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/latexbuilder.rb:107:in `column_begin'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/compiler.rb:661:in `compile_column'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/node.rb:284:in `to_doc'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `block in to_s_by'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `map'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `to_s_by'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/node.rb:12:in `to_doc'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/compiler.rb:417:in `convert_ast'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/compiler.rb:406:in `do_compile'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/lib/review/compiler.rb:398:in `compile'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/bin/review-compile-peg:157:in `block in _main'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/bin/review-compile-peg:153:in `each'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/bin/review-compile-peg:153:in `_main'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/bin/review-compile-peg:31:in `main'
	from /Users/vvakame/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/review-peg-0.2.0/bin/review-compile-peg:202:in `<top (required)>'
	from /Users/vvakame/.rbenv/versions/2.2.3/bin/review-compile-peg:23:in `load'
	from /Users/vvakame/.rbenv/versions/2.2.3/bin/review-compile-peg:23:in `<main>'
```

**Comment by vvakame** [comment]
コラムのタイトルが存在しない場合もそれとわかりづらいエラーになりました。

**Comment by takahashim** [comment]
こちら調べてみましたが、コラム周りは元々の仕様が微妙そうでした…
（コラムの参照用キーがエスケープ済みの形で格納されているのが問題のようなので、エスケープ前の文字列で格納するように変更しないとダメそう）
