### ISSUE TITLE
review-peg 0.2.0 @<title>{hoge}があるとコンパイルがコケる

### ISSUE THREAD

**Issue by mstssk** [kmuto/review#463]
```
$ review-compile-peg -v
review-compile-peg 0.2.0
$ cat test.re
= テスト章

@<title>{test}
$ review-compile-peg --target=latex test.re
/Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/latexbuilder.rb:684:in `node_inline_title': super: no superclass method `node_inline_title' for #<ReVIEW::LATEXBuilder:0x007fed9a848138> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/compiler.rb:808:in `compile_inline'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:138:in `to_doc'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `block in to_s_by'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `to_s_by'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:12:in `to_doc'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `block in to_s_by'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `to_s_by'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:12:in `to_doc'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:72:in `to_doc'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `block in to_s_by'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:24:in `to_s_by'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/node.rb:12:in `to_doc'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/compiler.rb:417:in `convert_ast'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/compiler.rb:406:in `do_compile'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/lib/review/compiler.rb:398:in `compile'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/bin/review-compile-peg:157:in `block in _main'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/bin/review-compile-peg:153:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/bin/review-compile-peg:153:in `_main'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/bin/review-compile-peg:31:in `main'
	from /Library/Ruby/Gems/2.0.0/gems/review-peg-0.2.0/bin/review-compile-peg:202:in `<top (required)>'
	from /usr/bin/review-compile-peg:23:in `load'
	from /usr/bin/review-compile-peg:23:in `<main>'
```

**Comment by takahashim** [comment]
こちらは #466 で修正されたはずです。
あとで0.2.1を出しておくのでご確認いただければ。

**Comment by vvakame** [comment]
0.2.2で修正を確認しましたー

```
$ review-compile-peg --target=latex test.re
\chapter{テスト章}
\label{chap:test}

テスト章
```

**Comment by mstssk** [comment]
ありがとうございます！ :smile:
