### ISSUE TITLE
review-compile -a --target=pdf でエラー

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#471]
``require "review/#{target}builder"`` でコケてるみたいです。

```
% review-compile -a --target=pdf   
/Users/kdmsnr/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- review/pdfbuilder (LoadError)
	from /Users/kdmsnr/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kdmsnr/work/review/bin/review-compile:192:in `load_strategy_class'
	from /Users/kdmsnr/work/review/bin/review-compile:167:in `_main'
	from /Users/kdmsnr/work/review/bin/review-compile:31:in `main'
	from /Users/kdmsnr/work/review/bin/review-compile:202:in `<main>'
```

**Comment by kdmsnr** [comment]
おっと、すみません。勘違い。
