### ISSUE TITLE
Windows+Ruby 2.2でreview-preprocが失敗する

### ISSUE THREAD

**Issue by muojp** [kmuto/review#488]
Windows 10、ChocolateyからインストールしたRuby 2.2.3にて

> review-preproc -r --tabwidth=2 foo.re

を実行すると以下のようなエラーを吐きます。

```
>> C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/lib/review/preprocessor.rb:116:in `===': invalid byte sequence in Windows-31J (
>> ArgumentError)
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/lib/review/preprocessor.rb:116:in `preproc'
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/lib/review/preprocessor.rb:102:in `process'
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/bin/review-preproc:120:in `block in preproc'
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/bin/review-preproc:119:in `open'
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/bin/review-preproc:119:in `preproc'
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/bin/review-preproc:82:in `block in main'
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/bin/review-preproc:74:in `each'
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/bin/review-preproc:74:in `main'
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/bin/review-preproc:32:in `sigmain'
>>      from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/review-1.7.2/bin/review-preproc:131:in `<top (required)>'
>>      from C:/tools/ruby22/bin/review-preproc:23:in `load'
>>      from C:/tools/ruby22/bin/review-preproc:23:in `<main>'
>> Exited with code: 1.
```

review-preproc.batの末尾を`@"C:\tools\ruby22\bin\ruby.exe" -Eutf-8 "%~dpn0" %*`に書き換えたら問題なく実行できましたが、このあたりってgemのパッケージ生成時に制御できるのでしょうか...?

**Comment by takahashim** [comment]
とりあえず、

* `set RUBYOPT=-EUTF-8`を実行して環境変数経由でオプションを指定する
* `chcp 65001`を実行してコマンドプロンプトの文字コードを変更する

という回避策があります。

とはいえreview-preprocで`review/extensions`をrequireするようにするのが筋ですよね…。

**Comment by kmuto** [comment]
これはなんとかなるのでしたっけ…

**Comment by kmuto** [comment]
Ruby1.8はもう考えなくてよいしUTF-8前提なら、いろいろopenのところでr:utf-8 としたら解決できるのでしょうか。

**Comment by kmuto** [comment]
標準出力のコードも変えないと、リダイレクトしたときにだめか…。Windowsでは-EUTF-8せよ、とするほうがよさそう？ batファイルってRe:VIEWから提供していましたっけ。

**Comment by kmuto** [comment]
78c00f1a852e3bf50c098c733bdc0f32e8098521 の修正でひとまず問題なくなっているようですが、mapfileなどはBOM消さないとだめそう。

**Comment by takahashim** [comment]
BOMについては、File.open(filename,"rb:BOM|utf-8")みたいにすると自動的に削除されるようです。
http://docs.ruby-lang.org/ja/2.1.0/method/Kernel/m/open.html

**Comment by kmuto** [comment]
PR #574 でBOM切り実装を入れてみようとしています。

**Comment by kmuto** [comment]
#574 マージ済み。解決した、はずです。
