### ISSUE TITLE
Ubuntu 14.04 LTSでビルドエラーが起きるケースがある

### ISSUE THREAD

**Issue by dmiyakawa** [kmuto/review#647]
https://github.com/TechBooster/C89-FirstStepReVIEW-v2/ 

が、Ubuntu 14.04 LTS ではなぜかreview-pdfmakerが失敗します。
Ubuntu 16.04 LTS, Debian jessie ではtexlive関連の同等のパッケージを入れれば成功することはわかっています。
RHEL/CentOS/Fedora系統では未検証です。

Re:VIEW本体のせいなのかインストールするパッケージのせいなのかはちょっと分かりませんので念のためIssue登録させてもらいました。

(以下、他作業中だったのでvenv配下ですが本題とは関係ないのでなでやかにスルーをお願いします)

```
$ cd /tmp
(venv)dev /tmp$ git clone git@github.com:TechBooster/C89-FirstStepReVIEW-v2.git
Cloning into 'C89-FirstStepReVIEW-v2'...
remote: Counting objects: 880, done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 880 (delta 32), reused 0 (delta 0), pack-reused 815
Receiving objects: 100% (880/880), 3.77 MiB | 1.41 MiB/s, done.
Resolving deltas: 100% (551/551), done.
Checking connectivity... done.
(venv)dev /tmp$ cd C89-FirstStepReVIEW-v2
(venv)dev /tmp/C89-FirstStepReVIEW-v2$ ls
articles  build-in-docker.sh  circle.yml  code  Gemfile  Gemfile.lock  Gruntfile.js  npm-shrinkwrap.json  package.json  README.md  setup.sh
(venv)dev /tmp/C89-FirstStepReVIEW-v2$ cd articles
(venv)dev /tmp/C89-FirstStepReVIEW-v2/articles$ review-pdfmaker --version
review-pdfmaker 2.0.0
(venv)dev /tmp/C89-FirstStepReVIEW-v2/articles$ review-pdfmaker config.yml
compiling preface.tex
compiling writing-book.tex
compiling setup.tex
compiling review-introduction.tex
warning: duplicate ID: image_sample (#<ReVIEW::Book::IndepImageIndex::Item:0x0000000204fe28>)
compiling configure.tex
compiling build.tex
compiling workflow.tex
compiling tips.tex
compiling contributors.tex
This is e-upTeX, Version 3.1415926-p3.4-u1.11-110825-2.6 (utf8.uptex) (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./book.tex
pLaTeX2e <2011/05/07u00>+0 (based on LaTeX2e <2011/06/27> patch level 0)
Babel <3.9h> and hyphenation patterns for 11 languages loaded.
(/usr/share/texlive/texmf-dist/tex/platex/jsclasses/jsbook.cls
Document Class: jsbook 2013/05/14 okumura
) (/usr/share/texlive/texmf-dist/tex/platex/japanese-otf-uptex/otf.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/platex/japanese-otf/ajmacros.sty))
(/usr/share/texmf/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/dvipdfmx-def/dvipdfmx.def))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)))
(/usr/share/texlive/texmf-dist/tex/latex/framed/framed.sty)
(/usr/share/texlive/texmf-dist/tex/latex/wrapfig/wrapfig.sty)
(/usr/share/texmf/tex/latex/lm/lmodern.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))
(/usr/share/texlive/texmf-dist/tex/platex/base/ascmac.sty
(/usr/share/texlive/texmf-dist/tex/platex/base/tascmac.sty))
(/usr/share/texlive/texmf-dist/tex/latex/float/float.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/alltt.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver: hdvipdfm.

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hdvipdfm.def
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/share/texlive/texmf-dist/tex/platex/pxjahyper/pxjahyper.sty)
(./techbooster-doujin.sty
(/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty
(/usr/share/texmf/tex/latex/pgf/basiclayer/pgf.sty
(/usr/share/texmf/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/share/texmf/tex/generic/pgf/utilities/pgfutil-common.tex)
(/usr/share/texmf/tex/generic/pgf/utilities/pgfutil-latex.def
(/usr/share/texlive/texmf-dist/tex/latex/ms/everyshi.sty))
(/usr/share/texmf/tex/generic/pgf/utilities/pgfrcs.code.tex))
(/usr/share/texmf/tex/latex/pgf/basiclayer/pgfcore.sty
(/usr/share/texmf/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsys.code.tex
(/usr/share/texmf/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texmf/tex/generic/pgf/utilities/pgfkeysfiltered.code.tex))
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsys-dvipdfmx.def
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsys-common-pdf.def)))
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.tex)
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsysprotocol.code.tex))
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcore.code.tex
(/usr/share/texmf/tex/generic/pgf/math/pgfmath.code.tex
(/usr/share/texmf/tex/generic/pgf/math/pgfmathcalc.code.tex
(/usr/share/texmf/tex/generic/pgf/math/pgfmathutil.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathparser.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.code.tex
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.basic.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.trigonometric.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.random.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.comparison.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.base.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.round.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex)))
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfloat.code.tex))
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepathconstruct.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepathusage.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorescopes.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoregraphicstate.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoretransformations.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorequick.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoreobjects.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepathprocessing.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoreexternal.code.tex))
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoretransparency.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex)))
(/usr/share/texmf/tex/generic/pgf/modules/pgfmoduleshapes.code.tex)
(/usr/share/texmf/tex/generic/pgf/modules/pgfmoduleplot.code.tex)
(/usr/share/texmf/tex/latex/pgf/compatibility/pgfcomp-version-0-65.sty)
(/usr/share/texmf/tex/latex/pgf/compatibility/pgfcomp-version-1-18.sty))
(/usr/share/texlive/texmf-dist/tex/latex/tools/verbatim.sty)
(/usr/share/texlive/texmf-dist/tex/latex/environ/environ.sty
(/usr/share/texlive/texmf-dist/tex/latex/trimspaces/trimspaces.sty))
(/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty
(/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbskins.code.tex
Library (tcolorbox): 'tcbskins.code.tex' version '2.70'
(/usr/share/texmf/tex/latex/pgf/frontendlayer/tikz.sty
(/usr/share/texmf/tex/latex/pgf/utilities/pgffor.sty
(/usr/share/texmf/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texmf/tex/generic/pgf/utilities/pgfkeys.code.tex))
(/usr/share/texmf/tex/generic/pgf/utilities/pgffor.code.tex))
(/usr/share/texmf/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
(/usr/share/texmf/tex/generic/pgf/libraries/pgflibraryplothandlers.code.tex)
(/usr/share/texmf/tex/generic/pgf/modules/pgfmodulematrix.code.tex)
(/usr/share/texmf/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopat
hs.code.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbskinsjigsaw.code.tex
Library (tcolorbox): 'tcbskinsjigsaw.code.tex' version '2.70'
)) (/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbbreakable.code.tex
Library (tcolorbox): 'tcbbreakable.code.tex' version '2.70'
) (/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbhooks.code.tex
Library (tcolorbox): 'tcbhooks.code.tex' version '2.70'
) (/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbtheorems.code.tex
Library (tcolorbox): 'tcbtheorems.code.tex' version '2.70'
) (/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbfitting.code.tex
Library (tcolorbox): 'tcbfitting.code.tex' version '2.70'
) (/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcblistingsutf8.code.tex
Library (tcolorbox): 'tcblistingsutf8.code.tex' version '2.70'
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/listingsutf8.sty
(/usr/share/texlive/texmf-dist/tex/latex/listings/listings.sty
(/usr/share/texlive/texmf-dist/tex/latex/listings/lstmisc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/listings/listings.cfg))

Package listingsutf8 Warning: Package loading is aborted because of missing \pd
f@unescapehex.
(listingsutf8)                It is provided by pdfTeX >= 1.30.

) (/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcblistings.code.tex
Library (tcolorbox): 'tcblistings.code.tex' version '2.70'
(/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcblistingscore.code.tex
Library (tcolorbox): 'tcblistingscore.code.tex' version '2.70'
)))) (/usr/share/texlive/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(./ulem.sty) (/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix
<2008/02/07> (tvz))
(/usr/share/texlive/texmf-dist/tex/latex/seqsplit/seqsplit.sty))
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def))
No file book.aux.
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
(I search kanjifont definition file: . . ) (I search font definition file: . .
. . . . . . ) (/usr/share/texmf/tex/latex/lm/t1lmr.fd)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))

Package hyperref Warning: Rerun to get /PageLabels entry.

ABD: EveryShipout initializing macros
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)
(/usr/share/texmf/tex/latex/lm/ot1lmr.fd)
(/usr/share/texmf/tex/latex/lm/omllmm.fd)
(/usr/share/texmf/tex/latex/lm/omslmsy.fd)
(/usr/share/texmf/tex/latex/lm/omxlmex.fd) [1] (./preface.tex [2]
(/usr/share/texmf/tex/latex/lm/t1lmtt.fd))

Package Fancyhdr Warning: \headheight is too small (14.22636pt):
 Make it at least 16.0pt.
 We now make it that large for the rest of the document.
 This may cause the page layout to be inconsistent, however.

[3] [4] (./writing-book.tex
第1章
<./images/writing-book/review-cover.png> [5]
(/usr/share/texmf/tex/latex/lm/ts1lmr.fd) [6] [7]) (./setup.tex [8]
第2章
<./images/setup/install-language-review.png> [9]
<./images/setup/language-review-grammar1.png>
<./images/setup/language-review-grammar2.png> [10]

! Package pgfkeys Error: I do not know the key '/tcb/sharp corners' and I am go
ing to ignore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.54 \begin{reviewcmd}

? q
OK, entering \batchmode/var/lib/gems/1.9.1/gems/review-2.0.0/lib/review/pdfmaker.rb:41:in `system_or_raise': failed to run command: uplatex  book.tex (RuntimeError)
    from /var/lib/gems/1.9.1/gems/review-2.0.0/lib/review/pdfmaker.rb:191:in `block (2 levels) in generate_pdf'
    from /var/lib/gems/1.9.1/gems/review-2.0.0/lib/review/pdfmaker.rb:190:in `times'
    from /var/lib/gems/1.9.1/gems/review-2.0.0/lib/review/pdfmaker.rb:190:in `block in generate_pdf'
    from /var/lib/gems/1.9.1/gems/review-2.0.0/lib/review/pdfmaker.rb:176:in `chdir'
    from /var/lib/gems/1.9.1/gems/review-2.0.0/lib/review/pdfmaker.rb:176:in `generate_pdf'
    from /var/lib/gems/1.9.1/gems/review-2.0.0/lib/review/pdfmaker.rb:130:in `execute'
    from /var/lib/gems/1.9.1/gems/review-2.0.0/lib/review/pdfmaker.rb:85:in `execute'
    from /var/lib/gems/1.9.1/gems/review-2.0.0/bin/review-pdfmaker:18:in `<top (required)>'
    from /usr/local/bin/review-pdfmaker:23:in `load'
    from /usr/local/bin/review-pdfmaker:23:in `<main>'
(venv)dev /tmp/C89-FirstStepReVIEW-v2/articles$ dpkg -l | grep -e texlive -e latex
ii  latex-beamer                         3.24-1                                  all          LaTeX class to produce presentations
ii  latex-cjk-all                        4.8.3+git20120914-2ubuntu1              all          installs all LaTeX CJK packages
ii  latex-cjk-chinese                    4.8.3+git20120914-2ubuntu1              amd64        Chinese module of LaTeX CJK
ii  latex-cjk-chinese-arphic-bkai00mp    1.23                                    all          AR PL KaitiM Big5 fonts for CJK
ii  latex-cjk-chinese-arphic-bsmi00lp    1.23                                    all          AR PL Mingti2L Big5 fonts for CJK
ii  latex-cjk-chinese-arphic-gbsn00lp    1.23                                    all          AR PL SungtiL GB fonts for CJK
ii  latex-cjk-chinese-arphic-gkai00mp    1.23                                    all          AR PL KaitiM GB fonts for CJK
ii  latex-cjk-common                     4.8.3+git20120914-2ubuntu1              amd64        LaTeX macro package for CJK (Chinese/Japanese/Korean)
ii  latex-cjk-japanese                   4.8.3+git20120914-2ubuntu1              amd64        Japanese module of LaTeX CJK
ii  latex-cjk-japanese-wadalab           0.20050817-16                           all          type1 and tfm DNP Japanese fonts for latex-cjk
ii  latex-cjk-korean                     4.8.3+git20120914-2ubuntu1              all          Korean module of LaTeX CJK
ii  latex-cjk-thai                       4.8.3+git20120914-2ubuntu1              all          Thai module of LaTeX CJK
ii  latex-xcolor                         2.11-1.1                                all          Easy driver-independent TeX class for color
ii  libpod-latex-perl                    0.61-1                                  all          module to convert Pod data to formatted LaTeX
ii  preview-latex-style                  11.87-1ubuntu2                          all          extraction of elements from LaTeX documents as graphics
ii  texlive-base                         2013.20140215-1                         all          TeX Live: Essential programs and files
ii  texlive-binaries                     2013.20130729.30972-2build3             amd64        Binaries for TeX Live
ii  texlive-extra-utils                  2013.20140215-2                         all          TeX Live: TeX auxiliary programs
ii  texlive-font-utils                   2013.20140215-2                         all          TeX Live: Graphics and font utilities
ii  texlive-fonts-recommended            2013.20140215-1                         all          TeX Live: Recommended fonts
ii  texlive-fonts-recommended-doc        2013.20140215-1                         all          TeX Live: Documentation files for texlive-fonts-recommended
ii  texlive-generic-recommended          2013.20140215-1                         all          TeX Live: Generic recommended packages
ii  texlive-lang-cjk                     2013.20140215-1                         all          TeX Live: Chinese/Japanese/Korean
ii  texlive-lang-other                   2013.20140215-1                         all          TeX Live: Other languages
ii  texlive-latex-base                   2013.20140215-1                         all          TeX Live: LaTeX fundamental packages
ii  texlive-latex-base-doc               2013.20140215-1                         all          TeX Live: Documentation files for texlive-latex-base
ii  texlive-latex-extra                  2013.20140215-2                         all          TeX Live: LaTeX additional packages
ii  texlive-latex-extra-doc              2013.20140215-2                         all          TeX Live: Documentation files for texlive-latex-extra
ii  texlive-latex-recommended            2013.20140215-1                         all          TeX Live: LaTeX recommended packages
ii  texlive-latex-recommended-doc        2013.20140215-1                         all          TeX Live: Documentation files for texlive-latex-recommended
ii  texlive-luatex                       2013.20140215-1                         all          TeX Live: LuaTeX packages
ii  texlive-pictures                     2013.20140215-1                         all          TeX Live: Graphics, pictures, diagrams
ii  texlive-pictures-doc                 2013.20140215-1                         all          TeX Live: Documentation files for texlive-pictures
ii  texlive-pstricks                     2013.20140215-2                         all          TeX Live: PSTricks
ii  texlive-pstricks-doc                 2013.20140215-2                         all          TeX Live: Documentation files for texlive-pstricks
(venv)dev /tmp/C89-FirstStepReVIEW-v2/articles$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
```

**Comment by takahashim** [comment]
なんとなく、

```
Package listingsutf8 Warning: Package loading is aborted because of missing \pd
f@unescapehex.
(listingsutf8)                It is provided by pdfTeX >= 1.30.
```

が問題なんじゃないかと思うんですが、`pdfTeX >= 1.30`とか言われてもuplatexではどうすればいいんだろう…

**Comment by kmuto** [comment]
これ、あまりどうにもならなそうなのでwontfixでいったんcloseしちゃっていいですかね…

**Comment by munepi** [comment]
これは、 @takahashim さんの「なんとなく」どおり、使おうとしている tcolorbox の key `tcb/sharp corners` が Ubuntu 14.04 LTSのdistro版TeX Liveに同梱されているtcolorbox v2.70 では、非対応だからです。実際に、TeX Live 201Y (Y=2, 3, 4, 5, 6) frozen, TeX Live 2017 currentで以下のとおりでした。tcolorbox v3.xあたりから、 `tcb/sharp corners` が使えるようになったようです。

```
$ grep -e "ProvidesPackage" -e "sharp corners" /opt/texlive/201?/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty 
/opt/texlive/2012/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:\ProvidesPackage{tcolorbox}[2013/03/13 version 2.02 text color boxes]
/opt/texlive/2013/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:\ProvidesPackage{tcolorbox}[2014/03/31 version 2.80 text color boxes]
/opt/texlive/2014/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:\ProvidesPackage{tcolorbox}[2015/03/16 version 3.50 text color boxes]
/opt/texlive/2014/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:  \begin{tcolorbox}[sharp corners,
/opt/texlive/2015/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:\ProvidesPackage{tcolorbox}[2016/02/29 version 3.90 text color boxes]
/opt/texlive/2015/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:  \begin{tcolorbox}[sharp corners,
/opt/texlive/2016/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:\ProvidesPackage{tcolorbox}[2017/02/24 version 4.02 text color boxes]
/opt/texlive/2016/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:  \begin{tcolorbox}[sharp corners,
/opt/texlive/2017/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:\ProvidesPackage{tcolorbox}[2017/04/25 version 4.03 text color boxes]
/opt/texlive/2017/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty:  \begin{tcolorbox}[sharp corners,
```

**Comment by kmuto** [comment]
ありがとうございます！ 今あえて14.04を新たに入れるケースはないでしょうし、14.04での解法も示していただきましたのでこれはwontfixでcloseします。
